#version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput && 
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
